### ISSUE TITLE
extra release time on oscillator can be surprising

### ISSUE THREAD

**Issue by pbaille** [ctford/cljs-bach#1]
paste from cljs.bach.synthesis:

``` clojure
(defn oscillator
  "A periodic wave."
  [type freq]
  (fn [context at duration]
    (source
      (doto (.createOscillator context)
        (-> .-frequency .-value (set! 0))
        (-> .-frequency (plug freq context at duration))
        (-> .-type (set! type))
        (.start at)
        (.stop (+ at duration 1.0)))))) <----- here
```

If I create an oscillator like this

``` 
(oscillator "sine" another-synth)
```

the extra second added (see the "here" mark) need to be added to another-synth, is this really wanted?

**Comment by pbaille** [comment]
BTW your lib is really elegant in my opinion :)

**Comment by ctford** [comment]
Hi @pbaille,

Sorry for the delayed response. I've been away from Github over the new year. Thanks for using CLJS Bach. I'm glad that you find it elegant - I like the web audio API, but I felt a need to have better ways of composing synths together, and CLJS Bach does that for me.

You've found a bit of the design that I'm unsure about, but I do have a reason. The motivation for it is that it allows for a note to have a release that lasts beyond its duration. So if you don't add that padding, then the release of e.g. an ADSR envelope either gets cut off as the oscillator stops, or you have to include the fading away of the note in the duration.

Neither of those options worked for me, so I added a margin of a second so that the oscillators continue to play even while the note is fading.

If you use an envelope to control when the note ends, rather than letting the oscillator run its course, does it cause the same problem? Can you think of a better way I could approach the problem?

**Comment by pbaille** [comment]
Sorry for the delay and thank you for the detailed answer. So far I have not any precise ideas on this but next time I use cljs bach I will try more stuffs in that direction and tell you if I find something.

**Comment by ctford** [comment]
As all the use cases I've come across use envelopes with the oscillators, and as envelopes hide the 1 second effect, I'm going to close this. Feel free to reopen or comment if you have a new insight.
