### ISSUE TITLE
Documentation for cljs-bach.synthesis.sample

### ISSUE THREAD

**Issue by chr15m** [ctford/cljs-bach#3]
I noticed in the pure-JS HTML example there is a function called `sample`:

https://github.com/ctford/cljs-bach/search?utf8=%E2%9C%93&q=sample

I would love to know more about what is possible with this.

**Comment by ctford** [comment]
The function `cljs_bach.synthesis.sample()` loads a sample over HTTP and plays it. Unfortunately the implementation is a little shaky because making an HTTP request is asynchronous. What it does now is to memoize (cache) that request so that it only makes it the first time, but still it can be glitchy.

The main logic of how this works is here - https://github.com/ctford/cljs-bach/blob/2215b8dccccfdeeb7920dda75de9cdfb40828919/src/cljs_bach/synthesis.cljs#L269

**Comment by ctford** [comment]
I've added this function to the README.

**Comment by chr15m** [comment]
@ctford did you push this up? I can't see it in the README.
